logging:
  level:
    com.liruo.communityforum: debug
server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: communityforum
  profiles:
    active: dev
  datasource:
    username: root
    password: hrh020403
    url: jdbc:mysql://localhost:3306/temp_post
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    format:
      time: yyyy-MM-dd HH:mm:ss、
  mail:
    #发送邮件服务器
    host: smtp.163.com
    #发送者的邮箱
    username: liruo_hrh@163.com
    #pop3/smtp/imap的授权码
    password: GEYZCCORPJLBFCXQ
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger/doc.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
    groups-order: desc
  api-docs:
    enabled: true
    groups:
      enabled: true
    version: openapi_3_0
    resolve-schema-properties: true
    path: /openapi/v3
  pre-loading-enabled: true
  group-configs:
    - group: community_forum
      packages-to-scan:
        - com.liruo.communityforum.controller
      paths-to-match:
        - /**
